// SPDX-License-Identifier: MIT
export { canonicalJsonBytes, CanonicalJsonError } from "./canonical-json.ts";
export type { CanonicalJsonErrorCodeV1 } from "./canonical-json.ts";
export { digestBytes, digestCanonical } from "./digest.ts";
export type { DigestDomainV1 } from "./digest.ts";
export { commitAttemptV1, faultAttemptV1, rejectAttemptV1 } from "./execution.ts";
export type {
  AssetPackDigestProjectionV1,
  AssetPackResolvedIdentityV1,
  AssetPackSourceIdentityV1,
  AssetPackV1,
  AssetPivotV1,
  AssetProviderEntryV1,
  AssetProviderRefV1,
  AssetSafeAreaV1,
  AssetSlotDefinitionV1,
  AssetUsageV1,
  ResolvedAssetEntryV1,
  ResolvedAssetManifestV1,
} from "./assets.ts";
export {
  createReadonlyViewSourceV1,
  createSaveSlotIdsV1,
  defaultManualSaveSlotCountV1,
  isPlayerWritableSaveSlotIdV1,
  isSaveSlotIdShapeV1,
  manualSaveSlotIdV1,
  manualSaveSlotIndexV1,
  maxManualSaveSlotCountV1,
  parseManualSaveSlotCountV1,
} from "./application.ts";
export type {
  DebugFixtureListResultV1,
  DebugToolsOperationResultV1,
  DebugToolsPortV1,
  GameApplicationPortV1,
  LeaseHandoffRequestId,
  ManualSaveSlotIdV1,
  MutableViewPublisherV1,
  PlayerDiagnosticsPortV1,
  PlayerPersistencePortV1,
  PlayerWritableSaveSlotIdV1,
  ReadonlyViewSourceV1,
  RuntimeCapabilitiesV1,
  RuntimeCapabilityIdV1,
  RuntimeCapabilityOperationResultV1,
  RuntimeCapabilityPortV1,
  SaveSlotIdV1,
  SemanticGamePortInputV1,
  SemanticGamePortSourceV1,
  SemanticGamePortV1,
  SemanticPublicationV1,
  SessionLeaseOwnerId,
  SessionLeasePortV1,
  SessionLifecyclePortV1,
} from "./application.ts";
export type {
  GamePackageV1,
  PatchSurfaceValueMapWitnessV1,
  ResolvedGameV1,
  ResolvedPatchValuesV1,
  StateContractManifestV1,
  StateContractModuleManifestV1,
  StateContractSchemaManifestV1,
  StateContractStableReferenceSetV1,
  StoryDefinitionV1,
  StoryPresentationFacetV1,
  StorySimulationFacetV1,
  StorySourceIdentityV1,
  StoryToolingEntryV1,
  StoryToolingSupportV1,
} from "./game-package.ts";
export type {
  BootstrapEntropyV1,
  GameBootstrapInputV1,
  GameCommandExecutorV1,
  GameDebugCommandExecutorV1,
  GameDebugCommandValidationResultV1,
  GameSimulationTypeMapV1,
  GameSimulationTypeWitnessV1,
  GameSimulationV1,
  GameplayModuleBindingV1,
  GameplayModuleDescriptorV1,
  GameplayModuleSurfaceV1,
  GameplayModuleTupleForSimulationV1,
  ModuleInvariantViolationV1,
  ModuleLocalInvariantV1,
  ModuleOwnerCapabilityV1,
  ModuleOwnerProposalEnvelopeV1,
  ModuleProposalResultV1,
  ModuleQueryCapabilityV1,
  StatefulGameplayModuleBindingV1,
  StatelessGameplayModuleBindingV1,
} from "./gameplay-module.ts";
export type {
  AppliedHotfixV1,
  GamePackageResolutionFailureCodeV1,
  GamePackageResolutionFailureV1,
  GamePackageResolutionResultV1,
  GameBootstrapResolutionResultV1,
  HotfixInstallContextV1,
  HotfixEntryV1,
  HotfixManifestV1,
  PatchReplacementPortV1,
  PatchReplacementValuesV1,
  PatchReplacementTraceV1,
  PatchSetIdentityV1,
  PatchSetAdoptionDeclarationV1,
  PatchSlotDescriptorV1,
  PatchSurfaceKindV1,
  PatchSymbolKindV1,
} from "./hotfix.ts";
export type { BuildProvenanceV1 } from "./provenance.ts";
export type {
  GameHostV1,
  HostAtomicCommitResultV1,
  HostAtomicRecordStoreV1,
  HostFilePortV1,
  HostFileSelectionResultV1,
  HostRecordKeyV1,
  HostRecordMutationV1,
  HostRecordNamespaceV1,
  HostRecordRevisionV1,
  HostStoredRecordV1,
  IsoUtcInstant,
} from "./host.ts";
export {
  canonicalPresentationJsonBytesV1,
  combineContentMaturityFlagsV1,
  emptyContentMaturityFlagsV1,
  findUnknownContentMaturityFlagsV1,
  isContentRequirementAllowedV1,
  parseAppearanceLayerId,
  parseAssetId,
  parseCharacterActivityId,
  parseCharacterExpressionId,
  parseCharacterId,
  parseCharacterPoseId,
  parseCharacterRigId,
  parseContentMaturityFlagBitV1,
  parseContentMaturityFlagId,
  parseContentMaturityFlagsV1,
  parseContentMaturityPolicyV1,
  parseContentPreferencePresetId,
  parseContentPreferenceV1,
  parseHitAreaId,
  parseHitMapId,
  parseInteractionBehaviorId,
  parseInteractionSurfaceId,
  parseInteractionTargetId,
  parseLocaleId,
  parseNormalizedCoordinateV1,
  parseNormalizedExtentV1,
  parsePositiveFiniteNumber,
  parsePresentationProviderId,
  parseStageSceneId,
  parseStageSceneVariantId,
  parseTextCatalogSetV1,
  parseTextId,
  requireContentPreferencePresetV1,
  setContentMaturityFlagV1,
} from "./presentation.ts";
export type {
  AppearanceLayerId,
  AssetId,
  CharacterActivityId,
  CharacterExpressionId,
  CharacterId,
  CharacterPoseId,
  CharacterRigId,
  ContentMaturityFlagBitV1,
  ContentMaturityFlagId,
  ContentMaturityFlagsV1,
  ContentMaturityPolicyV1,
  ContentPreferencePortV1,
  ContentPreferencePresetDescriptorV1,
  ContentPreferencePresetId,
  ContentPreferenceSetResultV1,
  ContentPreferenceV1,
  ContentRequirementV1,
  HitAreaId,
  HitMapId,
  InteractionBehaviorId,
  InteractionSurfaceId,
  InteractionTargetId,
  LocaleId,
  LocalizedTextCatalogV1,
  NormalizedCoordinateV1,
  NormalizedExtentV1,
  PositiveFiniteNumber,
  PresentationCatalogValidationCodeV1,
  PresentationCatalogValidationErrorV1,
  PresentationReadPortV1,
  PresentationProviderId,
  ResolvedAssetPresentationV1,
  ResolvedTextPresentationV1,
  RuntimeSessionStatusV1,
  RuntimeViewModelEnvelopeV1,
  SessionAnchorResultV1,
  SessionDispatchOperationResultV1,
  StageSceneId,
  StageSceneVariantId,
  TextCatalogSetV1,
  TextId,
} from "./presentation.ts";
export {
  emptyVersionStampV1,
  formatVersionStampV1,
  readVersionStampV1,
  versionStampGlobalKeyV1,
} from "./version-stamp.ts";
export type { VersionStampV1 } from "./version-stamp.ts";
export {
  createSaveRecordEnvelopeSchemaV1,
  exportedSaveSchemaV1,
  parseSaveAnnotationV1,
  parseSaveNoteV1,
  saveAnnotationLimitsV1,
  saveJsonLimitsV1,
  sessionLeaseStatusSchemaV1,
} from "./persistence.ts";
export type {
  ExportedSaveV1,
  SaveAnnotationV1,
  ImportCompatibilityOutcomeV1,
  ImportCompatibilityWarningV1,
  ImportRejectionCodeV1,
  ImportValidationErrorCodeV1,
  PersistenceOperationResultV1,
  PersistenceStatusV1,
  SaveCodecContextV1,
  SaveCompatibilityClassificationInputV1,
  SaveCompatibilityClassificationV1,
  SaveCompatibilityKeyV1,
  SaveCompatibilityMismatchV1,
  SaveExportOperationResultV1,
  SaveImportInvariantViewV1,
  SaveImportValidationContextV1,
  SaveImportValidationResultV1,
  SaveRecordDecodeRejectionCodeV1,
  SaveRecordDecodeResultV1,
  SaveRecordEnvelopeV1,
  SaveSlotHealthV1,
  SaveSlotSummaryV1,
  SaveWriteReasonV1,
  SessionLeaseOperationResultV1,
  SessionLeaseStatusV1,
  SimulationAdoptionV1,
} from "./persistence.ts";
export {
  createDebugBundleEnvelopeSchemaV1,
  createDebugUiContextSchemaV1,
  DebugBundleEnvelopeSchemaFailureV1,
  debugBundleJsonLimitsV1,
  debugPresentationLimitsV1,
  exportedDebugBundleSchemaV1,
  runtimeOperationFaultSchemaV1,
} from "./diagnostics.ts";
export type {
  AssetLoadFaultCodeV1,
  CommandLogEntryBaseV1,
  CommandLogEntryEnvelopeV1,
  DebugBundleEnvelopeV1,
  DebugBundleEnvelopeSchemaFailureCodeV1,
  DebugBundleEnvelopeSchemaInputV1,
  DebugPresentationRendererSummaryV1,
  DebugPresentationSummaryV1,
  DebugUiContextCurrentIdentityV1,
  DebugUiContextRecordedIdentityV1,
  DebugUiContextUseClassificationV1,
  DebugUiContextUseMismatchReasonV1,
  DebugUiContextV1,
  DebugUiSessionProjectionInputV1,
  DebugUiSessionSummaryV1,
  ExportedDebugBundleV1,
  PersistenceFaultCodeV1,
  RuntimeFaultBaseV1,
  RuntimeFaultCodeV1,
  RuntimeOperationFaultV1,
  UiFaultCodeV1,
} from "./diagnostics.ts";
export type {
  CommandExecutionAttemptEnvelopeV1,
  CommandExecutionDiagnosticsEnvelopeV1,
  CommandExecutionResultEnvelopeV1,
} from "./execution.ts";
export { createTransactionalRngV1, rngStateV1Schema } from "./rng.ts";
export type { RngDrawTraceV1, RngStateV1, RuleDrawRequestV1, RuleRngV1 } from "./rng.ts";
export {
  createGameSnapshotEnvelopeSchemaV1,
  createPristineRunIntegrityV1,
  runIntegrityV1Schema,
} from "./snapshot.ts";
export type { GameSnapshotEnvelopeV1, RunIntegrityReasonV1, RunIntegrityV1 } from "./snapshot.ts";
export { parseStrictJson, parseStrictJsonLimitsV1 } from "./strict-json.ts";
export type {
  StrictJsonErrorCodeV1,
  StrictJsonErrorV1,
  StrictJsonLimitsInputV1,
  StrictJsonLimitsV1,
  StrictJsonObjectV1,
  StrictJsonPrimitiveV1,
  StrictJsonResultV1,
  StrictJsonValueV1,
} from "./strict-json.ts";
export {
  parseDigest,
  parseModuleId,
  parseNonNegativeSafeInteger,
  parseNonZeroUint32,
  parsePositiveSafeInteger,
  parseRunId,
  parseStateSlotId,
  parseStoryId,
} from "./values.ts";
export type {
  Brand,
  DeepReadonly,
  Digest,
  ModuleId,
  NonNegativeSafeInteger,
  NonZeroUint32,
  PositiveSafeInteger,
  RunId,
  RuntimeSchemaV1,
  SafeInteger,
  StateSlotId,
  StoryId,
} from "./values.ts";
export {
  createSemanticStageStateV1,
  defaultStageCameraV1,
  defaultStageLayerTransformV1,
  defaultStagePlacementV1,
  digestSemanticStageStateV1,
  parseSemanticStageStateV1,
  parseStageAppearanceV1,
  parseStageCameraV1,
  parseStageContentIdV1,
  parseStageIdV1,
  parseStageLayerIdV1,
  parseStageLayerTransformV1,
  parseStagePlacementV1,
  parseStageTagV1,
  semanticStageContractRevisionV1,
} from "./semantic-stage.ts";
export type {
  CreateSemanticStageStateInputV1,
  SemanticStageStateV1,
  StageAppearanceV1,
  StageCameraV1,
  StageContentIdV1,
  StageEntryV1,
  StageIdV1,
  StageLayerIdV1,
  StageLayerTransformV1,
  StageLayerV1,
  StagePlacementV1,
  StageTagV1,
} from "./semantic-stage.ts";
export { parseStageMutationV1, reduceStageMutationsV1 } from "./semantic-stage-reducer.ts";
export type {
  StageMutationBatchOutcomeV1,
  StageMutationRejectionCodeV1,
  StageMutationRejectionV1,
  StageMutationV1,
} from "./semantic-stage-reducer.ts";
export { projectStageRenderTargetV1, stageFallbackRendererIdV1 } from "./stage-render-target.ts";
export { createAssetDemandPlanV1 } from "./asset-demand.ts";
export type {
  AssetDemandEntryV1,
  AssetDemandPlanV1,
  AssetDemandPriorityV1,
  AssetDemandRetentionV1,
  AssetDemandRetryPolicyV1,
  CreateAssetDemandPlanInputV1,
  TransientEffectRequestV1,
  TransientEffectV1,
} from "./asset-demand.ts";
export {
  lintNarrativeGraphV1,
  parseNarrativeGraphNodeV1,
  parseNarrativeGraphV1,
} from "./narrative-graph.ts";
export { emptyNarrativeDependenciesV1 } from "./narrative-graph.ts";
export type {
  NarrativeGraphDependenciesV1,
  NarrativeGraphNodeKindV1,
  NarrativeGraphNodeV1,
  NarrativeGraphV1,
  NarrativeLintCodeV1,
} from "./narrative-graph.ts";
export {
  createNarrativeGraphBuilderV1,
  defaultNarrativePredictionBudgetV1,
  narrativePredictionToDemandPlanV1,
  predictNarrativeDependenciesV1,
} from "./narrative-prediction.ts";
export type {
  NarrativeGraphBuilderNodeInputV1,
  NarrativeGraphBuilderV1,
  NarrativePredictionBudgetV1,
  NarrativePredictionV1,
} from "./narrative-prediction.ts";
export {
  appendNarrativeHistoryV1,
  emptyNarrativeHistoryV1,
  narrativeHistoryMaxEntriesV1,
  parseNarrativeHistoryEntryV1,
  parseNarrativeHistoryV1,
} from "./narrative-history.ts";
export type {
  NarrativeHistoryEntryKindV1,
  NarrativeHistoryEntryV1,
  NarrativeHistoryV1,
} from "./narrative-history.ts";
export {
  parseAudioAssetSlotV1,
  parseAudioChannelIntentV1,
  parseAudioIntentV1,
  parseAudioProviderEntryV1,
  parseVoiceIntentV1,
  resolveAudioManifestV1,
  silentAudioIntentV1,
} from "./media-audio.ts";
export type {
  AudioAssetSlotV1,
  AudioChannelIntentV1,
  AudioIntentV1,
  AudioMediaKindV1,
  AudioMediaTypeV1,
  AudioProviderEntryV1,
  ResolvedAudioAssetEntryV1,
  ResolvedAudioManifestV1,
  VoiceIntentV1,
  VoiceStopPolicyV1,
} from "./media-audio.ts";
export {
  evaluateInteractionResolutionV1,
  interactionOccurrenceIdV1,
  parseInteractionJsonObjectV1,
  parseInteractionOccurrenceIdV1,
  parseInteractionResolutionV1,
  parsePendingInteractionV1,
} from "./pending-interaction.ts";
export type {
  InteractionChoiceOptionV1,
  InteractionRejectionCodeV1,
  InteractionResolutionContextV1,
  InteractionResolutionOutcomeV1,
  InteractionResolutionV1,
  PendingInteractionBaseV1,
  PendingInteractionV1,
} from "./pending-interaction.ts";
export { diffPlainDataV1 } from "./plain-data-diff.ts";
export type { PlainDataDiffEntryV1 } from "./plain-data-diff.ts";
export {
  drawFromEventPoolV1,
  EventPoolErrorV1,
  evaluateEventConditionV1,
  parseEventConditionV1,
} from "./event-pool.ts";
export type {
  EventConditionV1,
  EventPoolCandidateV1,
  EventPoolContextV1,
  EventPoolDrawExplanationV1,
  EventPoolDrawInputV1,
  EventPoolDrawResultV1,
} from "./event-pool.ts";
export {
  ContentDatabaseErrorV1,
  createContentDatabaseV1,
  defineContentTableV1,
} from "./content-database.ts";
export type {
  AnyContentTableDefinitionV1,
  ContentConditionV1,
  ContentDatabaseV1,
  ContentQueryV1,
  ContentTableDefinitionV1,
  ContentTableViewV1,
  ContentWhereV1,
} from "./content-database.ts";
export { parseStageTransitionDefinitionV1 } from "./stage-transition.ts";
export {
  TimelineDefinitionErrorV1,
  evaluateTimelineAtV1,
  parseTimelineDefinitionV1,
  timelineChannelBaselineV1,
  timelineDurationV1,
  timelineStepDurationV1,
} from "./timeline.ts";
export type {
  TimelineCatalogV1,
  TimelineChannelValueV1,
  TimelineDefinitionV1,
  TimelineEasingV1,
  TimelinePropertyV1,
  TimelineSampleV1,
  TimelineStepV1,
  TimelineTargetV1,
} from "./timeline.ts";
export { timelineV1 } from "./timeline-builder.ts";
export type {
  StageTargetChangeV1,
  StageTransitionCatalogV1,
  StageTransitionDefinitionV1,
  StageTransitionEasingV1,
  StageTransitionInputPolicyV1,
  StageTransitionInterruptionV1,
  StageTransitionKindV1,
  StageTransitionReadinessV1,
  StageTransitionReducedMotionV1,
} from "./stage-transition.ts";
export type {
  StageContentCatalogV1,
  StageContentResolutionV1,
  StageHitRegionV1,
  StageRenderEntryV1,
  StageRenderLayerV1,
  StageRenderProjectionV1,
  StageRenderTargetV1,
} from "./stage-render-target.ts";
