// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// Generated by scripts/update-rule-source-digests.mts. Do not edit manually.

export const pocDemandPreviewProviderSourceDigestV1 =
  "sha256:9d3f607dfeb11fe2441fe6b43eaf2b07cf3a409fe3e0c457cd9049e98c9895cc";

export const pocDemandResolveProviderSourceDigestV1 =
  "sha256:fa73c2b7af6005efbd3315aaf26ddc4de3ba91ec400238511ad936d4a660849a";

export const pocTavernPreviewProviderSourceDigestV1 =
  "sha256:2b7ea79ff8eb6e193b032c5da69e1cc1d8e1346ef4f4f7e5d17f050a4b5e3a76";

export const pocTavernSettleProviderSourceDigestV1 =
  "sha256:9a03d4be7421fea7c7d7d8c1ab13ce46f798835fb0dc0159ed8ad9d9851ddab1";

export const pocChecksDescribeProviderSourceDigestV1 =
  "sha256:5b9865ae6ad755c48e8ed94ed17e1f23af2e5f4369f79f2fa121a62623b26d2e";

export const pocChecksResolveProviderSourceDigestV1 =
  "sha256:fbc2b50bcd849e18920e18db5e4598bde760537f9d6c525409d0f98338ba3370";

export const pocEndingsEvaluateProviderSourceDigestV1 =
  "sha256:4e243b5d8aa19d1e1a151efb7a3291249b13bedb776e4f02035f7010414339b4";
