// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// Generated by scripts/update-rule-source-digests.mts. Do not edit manually.

export const pocDemandPreviewProviderSourceDigestV1 =
  "sha256:9d68bd3a8079e646c2f456d18250557d7b6884c8d8f7158798b8dfcbf9841df8";

export const pocDemandResolveProviderSourceDigestV1 =
  "sha256:ac7dcb147c60159e49ce65b428b98f35142196a14e6f29179a937da193a17361";

export const pocTavernPreviewProviderSourceDigestV1 =
  "sha256:041b6923df93bacdad4e9ee8c35339957c6906ac08d8d509903785465fd7d182";

export const pocTavernSettleProviderSourceDigestV1 =
  "sha256:a171fa0fe5fd1ee02c56b1cec542671fea2d1fe0d265fd64fd7db667a203bff4";

export const pocChecksDescribeProviderSourceDigestV1 =
  "sha256:c751840680f20de0451c4dfc74b2125bfeaf8da0896b65448f0cd8af333054e9";

export const pocChecksResolveProviderSourceDigestV1 =
  "sha256:601664072a9fdf1e7a9f9ac7dd3175273cd3517b8dfe2592899a9ca9788926c2";

export const pocEndingsEvaluateProviderSourceDigestV1 =
  "sha256:08f06aeb07716f85f2ff29bc5a6cb444700d544adc95911a12b711f790e9faaf";
