// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// Generated by scripts/update-rule-source-digests.mts. Do not edit manually.

export const pocDemandPreviewProviderSourceDigestV1 =
  "sha256:f46cbc470f0fe596ead4e98bf7a41f785647bc7743b67eb71e22e2b1d12bc27e";

export const pocDemandResolveProviderSourceDigestV1 =
  "sha256:cb5c30b312f3ca4a243f45b622741cf3855126fb18c7648bdc4302e5386f342e";

export const pocTavernPreviewProviderSourceDigestV1 =
  "sha256:5bafc459f0470307fb48b2e46086d794d54bf2790bbccc860e5daa33cc406f3d";

export const pocTavernSettleProviderSourceDigestV1 =
  "sha256:d10328851c76b850ff9ed15003b3df7dc2e22754bb2b03fb0429fa3a9a36741f";

export const pocChecksDescribeProviderSourceDigestV1 =
  "sha256:343b61766611ac29ca722cf475d830e5713588ee0d853dedd8ae8246f8ca30c8";

export const pocChecksResolveProviderSourceDigestV1 =
  "sha256:3a3cb58f8d44d824b5df5fad56bebb67423ea5bf48675fd38d10e80a986c886f";

export const pocEndingsEvaluateProviderSourceDigestV1 =
  "sha256:dfd5724dc2227c50a5f64e75b8924e5e6dc3407494f66914f0cc2f8457eaaa2d";
