// SPDX-License-Identifier: MIT
import type { Plugin, ViteDevServer } from "vite";

import type { ProjectModuleRefV1 } from "../project/config-types.ts";
import { accessibleApplicationBootShellHtmlV1 } from "../desktop/application-bootstrap-html.mts";

/**
 * The dev-only SillyMaker Inspector page: `/__sillymaker/inspector/` serves an
 * HTML shell (run through the dev server's HTML transforms so the Vite
 * client and the React preamble are injected) whose module entry mounts
 * `@sillymaker/studio` with the application's declared Inspector binding.
 * `apply: "serve"` keeps every part of this out of builds, previews, and
 * the player bundle; the binding module is only ever imported here.
 */

export const inspectorPageUrlV1 = "/__sillymaker/inspector/";

/** HTML contract with the game-page DevDock Inspector shortcut. */
export const inspectorPageMetaNameV1 = "sillymaker-inspector";

/** @internal Stable browser-facing IDs consumed by the dev page and build-graph measurement. */
export const inspectorEntryIdInternalV1 = "/__sillymaker/inspector-entry.tsx";
export const embeddedAuthorEntryIdInternalV1 = "/__sillymaker/embedded-author-entry.ts";
export const embeddedAuthorRuntimeIdInternalV1 = "/__sillymaker/embedded-author-runtime.tsx";

const inspectorAuthoringBuildMeasurementPrefixInternalV1 =
  "\0sillymaker:inspector-authoring-build:";

/** @internal Generated dev-only Author entry document. */
export function createInspectorPageHtmlInternalV1(): string {
  return [
    "<!doctype html>",
    '<html lang="zh-CN">',
    "<head>",
    '<meta charset="utf-8" />',
    '<meta name="viewport" content="width=device-width, initial-scale=1" />',
    "<title>SillyMaker Inspector</title>",
    "</head>",
    "<body>",
    accessibleApplicationBootShellHtmlV1({
      containerId: "sillymaker-application-boot-shell",
      accessibleName: "SillyMaker Inspector 启动状态",
      statusText: "SillyMaker Inspector 正在启动…",
      bootstrap: { revision: 1, entry: "author", target: "browser" },
    }),
    '<div id="sillymaker-inspector-root"></div>',
    `<script type="module" src="${inspectorEntryIdInternalV1}"></script>`,
    "</body>",
    "</html>",
    "",
  ].join("\n");
}

function inspectorEntrySourceV1(inspector: ProjectModuleRefV1): string {
  const bindingModuleId = `/${inspector.module}`;
  return [
    "// Generated by sillymaker:inspector (vite dev only).",
    'import { createDevServerAuthoringSceneIoV1 } from "@sillymaker/studio";',
    'import { createInspectorToolingHmrCoordinatorV1, createInspectorToolingLiveCompositionV1, createInspectorToolingReactPublicationV1 } from "@sillymaker/studio/composition";',
    'import { createDevServerMotionIoV1 } from "@sillymaker/ui/debug/dev-source-client";',
    'import { createWebApplicationStartupDiagnosticsControllerInternalV1, readApplicationBootstrapConfigFromDocumentInternalV1 } from "@sillymaker/web/internal/application-startup";',
    `import { ${inspector.exportName} as bindingV1 } from ${JSON.stringify(bindingModuleId)};`,
    "",
    "const reportInspectorFailureV1 = (errorV1) => {",
    '  console.error("SillyMaker Inspector live composition failed", errorV1);',
    "};",
    "const startupDiagnosticsV1 = createWebApplicationStartupDiagnosticsControllerInternalV1(document);",
    'let startupFailureReasonV1: "bootstrap_config" | "required_domain" | "presentation" = "bootstrap_config";',
    "let disposeReactPublicationV1: (() => void) | null = null;",
    "let disposeCompositionV1: (() => Promise<void>) | null = null;",
    "try {",
    '  const bootstrapConfigV1 = readApplicationBootstrapConfigFromDocumentInternalV1(document, "author");',
    '  if (bootstrapConfigV1.target !== "browser") throw new TypeError("unsupported Inspector target");',
    '  startupFailureReasonV1 = "required_domain";',
    "  const sceneIoV1 = createDevServerAuthoringSceneIoV1();",
    "  const motionIoV1 = createDevServerMotionIoV1();",
    "  const compositionV1 = createInspectorToolingLiveCompositionV1({",
    '    profileId: "sillymaker.inspector.live",',
    "    onDiagnostic: reportInspectorFailureV1,",
    "  });",
    "  disposeCompositionV1 = () => compositionV1.dispose();",
    "  let revisionV1 = 1;",
    "  const initialPlanV1 = await compositionV1.mount({",
    "    revision: revisionV1,",
    "    binding: bindingV1,",
    "    sceneIo: sceneIoV1,",
    "    motionIo: motionIoV1,",
    "  });",
    "  startupDiagnosticsV1.signalRequiredDomainReady();",
    '  startupFailureReasonV1 = "presentation";',
    '  const container = document.getElementById("sillymaker-inspector-root");',
    '  if (container === null) throw new Error("inspector root element missing");',
    "  const reactPublicationV1 = createInspectorToolingReactPublicationV1({",
    "    container,",
    "    reportFailure: reportInspectorFailureV1,",
    "  });",
    "  disposeReactPublicationV1 = () => reactPublicationV1.dispose();",
    "  await reactPublicationV1.mount(initialPlanV1);",
    "",
    "  if (import.meta.hot !== undefined) {",
    "    const hmrV1 = createInspectorToolingHmrCoordinatorV1({",
    "      composition: compositionV1,",
    "      resolveRoot(moduleV1) {",
    '        if (moduleV1 === undefined) throw new TypeError("accepted Inspector module missing");',
    `        const nextBindingV1 = moduleV1[${JSON.stringify(inspector.exportName)}];`,
    '        if (nextBindingV1 === undefined) throw new TypeError("accepted Inspector binding missing");',
    "        revisionV1 += 1;",
    "        return {",
    "          revision: revisionV1,",
    "          binding: nextBindingV1,",
    "          sceneIo: sceneIoV1,",
    "          motionIo: motionIoV1,",
    "        };",
    "      },",
    "      publish: (planV1, signalV1) => reactPublicationV1.publish(planV1, signalV1),",
    "      disposeRoot: () => reactPublicationV1.dispose(),",
    "      reportFailure: reportInspectorFailureV1,",
    "    });",
    `    import.meta.hot.accept(${JSON.stringify(bindingModuleId)}, (moduleV1) => {`,
    "      hmrV1.accept(moduleV1);",
    "    });",
    "    import.meta.hot.dispose(() => {",
    "      startupDiagnosticsV1.dispose();",
    "      void hmrV1.dispose();",
    "    });",
    "  }",
    "",
    '  startupDiagnosticsV1.signalFirstProductCommit("presentation");',
    "} catch (errorV1) {",
    "  try {",
    "    disposeReactPublicationV1?.();",
    "  } catch (disposeErrorV1) {",
    "    reportInspectorFailureV1(disposeErrorV1);",
    "  }",
    "  if (disposeCompositionV1 !== null) {",
    "    try {",
    "      await disposeCompositionV1();",
    "    } catch (disposeErrorV1) {",
    "      reportInspectorFailureV1(disposeErrorV1);",
    "    }",
    "  }",
    "  reportInspectorFailureV1(errorV1);",
    "  startupDiagnosticsV1.signalTerminalStartupFailure({",
    "    reason: startupFailureReasonV1,",
    "    retry() {",
    "      globalThis.location.reload();",
    "    },",
    "  });",
    "}",
    "",
  ].join("\n");
}

function embeddedAuthorEntrySourceV1(): string {
  return [
    "// Generated by sillymaker:inspector (vite dev only; resident lightweight launcher).",
    'const containerV1 = document.createElement("div");',
    'containerV1.id = "sillymaker-embedded-author-root";',
    'containerV1.dataset.sillymakerEmbeddedAuthor = "launcher";',
    'const openV1 = document.createElement("button");',
    'const mountV1 = document.createElement("div");',
    'openV1.type = "button";',
    'openV1.className = "silly-button";',
    'openV1.textContent = "打开内嵌创作";',
    'openV1.dataset.embeddedAuthoringActivate = "true";',
    'openV1.setAttribute("aria-label", "打开内嵌创作");',
    'mountV1.dataset.sillymakerEmbeddedAuthorMount = "true";',
    "containerV1.append(openV1, mountV1);",
    "document.body.append(containerV1);",
    "let activationV1 = null;",
    'openV1.addEventListener("click", () => {',
    "  if (activationV1 !== null) return;",
    "  openV1.disabled = true;",
    `  activationV1 = import(${JSON.stringify(embeddedAuthorRuntimeIdInternalV1)})`,
    "    .then(async (moduleV1) => {",
    "      const mountedV1 = await moduleV1.mountEmbeddedAuthoringV1(mountV1);",
    '      containerV1.dataset.sillymakerEmbeddedAuthor = "mounted";',
    "      openV1.remove();",
    "      return mountedV1;",
    "    })",
    "    .catch((errorV1) => {",
    "      activationV1 = null;",
    "      mountV1.replaceChildren();",
    "      openV1.disabled = false;",
    '      console.error("SillyMaker embedded Authoring Host failed", errorV1);',
    "      throw errorV1;",
    "    });",
    "  void activationV1.catch(() => undefined);",
    "});",
    "",
  ].join("\n");
}

function embeddedAuthorRuntimeSourceV1(inspector: ProjectModuleRefV1): string {
  const bindingModuleId = `/${inspector.module}`;
  return [
    "// Generated by sillymaker:inspector (vite dev only; loaded on first author request).",
    'import { createDevServerAuthoringSceneIoV1 } from "@sillymaker/studio";',
    'import { createInspectorToolingHmrCoordinatorV1, createInspectorToolingLiveCompositionV1, createInspectorToolingReactPublicationV1 } from "@sillymaker/studio/composition";',
    'import { createDevServerMotionIoV1 } from "@sillymaker/ui/debug/dev-source-client";',
    `import { ${inspector.exportName} as bindingV1 } from ${JSON.stringify(bindingModuleId)};`,
    "",
    "let mountedV1 = null;",
    "export function mountEmbeddedAuthoringV1(containerV1) {",
    "  if (mountedV1 !== null) return mountedV1;",
    "  const attemptV1 = (async () => {",
    "    let compositionV1 = null;",
    "    let publicationV1 = null;",
    "    try {",
    "    const reportFailureV1 = (errorV1) => {",
    '      console.error("SillyMaker embedded Authoring Host live composition failed", errorV1);',
    "    };",
    "    const sceneIoV1 = createDevServerAuthoringSceneIoV1();",
    "    const motionIoV1 = createDevServerMotionIoV1();",
    "    compositionV1 = createInspectorToolingLiveCompositionV1({",
    '      profileId: "sillymaker.authoring-host.embedded.live",',
    "      onDiagnostic: reportFailureV1,",
    "    });",
    "    let revisionV1 = 1;",
    "    const initialPlanV1 = await compositionV1.mount({",
    "      revision: revisionV1,",
    "      binding: bindingV1,",
    "      sceneIo: sceneIoV1,",
    "      motionIo: motionIoV1,",
    "    });",
    "    publicationV1 = createInspectorToolingReactPublicationV1({",
    "      container: containerV1,",
    '      mode: "embedded",',
    "      reportFailure: reportFailureV1,",
    "    });",
    "    await publicationV1.mount(initialPlanV1);",
    "    if (import.meta.hot !== undefined) {",
    "      const hmrV1 = createInspectorToolingHmrCoordinatorV1({",
    "        composition: compositionV1,",
    "        resolveRoot(moduleV1) {",
    '          if (moduleV1 === undefined) throw new TypeError("accepted Inspector module missing");',
    `          const nextBindingV1 = moduleV1[${JSON.stringify(inspector.exportName)}];`,
    '          if (nextBindingV1 === undefined) throw new TypeError("accepted Inspector binding missing");',
    "          revisionV1 += 1;",
    "          return {",
    "            revision: revisionV1,",
    "            binding: nextBindingV1,",
    "            sceneIo: sceneIoV1,",
    "            motionIo: motionIoV1,",
    "          };",
    "        },",
    "        publish: (planV1, signalV1) => publicationV1.publish(planV1, signalV1),",
    "        disposeRoot: () => publicationV1.dispose(),",
    "        reportFailure: reportFailureV1,",
    "      });",
    `      import.meta.hot.accept(${JSON.stringify(bindingModuleId)}, (moduleV1) => {`,
    "        hmrV1.accept(moduleV1);",
    "      });",
    "      import.meta.hot.dispose(() => { void hmrV1.dispose(); });",
    "    }",
    "      return { publication: publicationV1, composition: compositionV1 };",
    "    } catch (errorV1) {",
    "      publicationV1?.dispose();",
    "      await compositionV1?.dispose();",
    "      throw errorV1;",
    "    }",
    "  })();",
    "  mountedV1 = attemptV1;",
    "  void attemptV1.catch(() => {",
    "    if (mountedV1 === attemptV1) mountedV1 = null;",
    "  });",
    "  return attemptV1;",
    "}",
    "",
  ].join("\n");
}

function inspectorVirtualSourceInternalV1(
  inspector: ProjectModuleRefV1,
  id: string,
): string | null {
  if (id === inspectorEntryIdInternalV1) return inspectorEntrySourceV1(inspector);
  if (id === embeddedAuthorEntryIdInternalV1) return embeddedAuthorEntrySourceV1();
  if (id === embeddedAuthorRuntimeIdInternalV1) {
    return embeddedAuthorRuntimeSourceV1(inspector);
  }
  return null;
}

function isInspectorVirtualIdInternalV1(id: string): boolean {
  return id === inspectorEntryIdInternalV1 || id === embeddedAuthorEntryIdInternalV1 ||
    id === embeddedAuthorRuntimeIdInternalV1;
}

/**
 * @internal Build-only measurement of the generated Author entries.
 * The NUL-prefixed resolved IDs keep receipt normalization truthful without
 * treating the browser-facing `/__sillymaker/*` URLs as filesystem paths.
 */
export function inspectorAuthoringBuildMeasurementPluginInternalV1(
  inspector: ProjectModuleRefV1,
): Plugin {
  return {
    name: "sillymaker:inspector-authoring-build-measurement",
    apply: "build",
    enforce: "pre",
    resolveId(id) {
      if (id.startsWith(inspectorAuthoringBuildMeasurementPrefixInternalV1)) return id;
      return isInspectorVirtualIdInternalV1(id)
        ? `${inspectorAuthoringBuildMeasurementPrefixInternalV1}${id}`
        : null;
    },
    load(id) {
      if (!id.startsWith(inspectorAuthoringBuildMeasurementPrefixInternalV1)) return null;
      return inspectorVirtualSourceInternalV1(
        inspector,
        id.slice(inspectorAuthoringBuildMeasurementPrefixInternalV1.length),
      );
    },
  };
}

/** The `vite dev`-only Inspector page plugin; absent when no binding is declared. */
export function inspectorPluginV1(inspector: ProjectModuleRefV1): Plugin {
  return {
    name: "sillymaker:inspector",
    apply: "serve",
    resolveId(id) {
      return isInspectorVirtualIdInternalV1(id) ? id : null;
    },
    load(id) {
      return inspectorVirtualSourceInternalV1(inspector, id);
    },
    transformIndexHtml: {
      order: "pre",
      handler(html) {
        // The Inspector page is the destination, not the advertisement.
        if (html.includes('id="sillymaker-inspector-root"')) return html;
        return {
          html,
          tags: [
            {
              tag: "meta",
              attrs: {
                name: inspectorPageMetaNameV1,
                content: inspectorPageUrlV1,
              },
              injectTo: "head",
            },
            {
              tag: "script",
              attrs: {
                type: "module",
                src: embeddedAuthorEntryIdInternalV1,
              },
              injectTo: "body",
            },
          ],
        };
      },
    },
    configureServer(server: ViteDevServer) {
      server.middlewares.use((request, response, next) => {
        const [pathname = ""] = (request.url ?? "").split("?", 2);
        if (
          pathname !== inspectorPageUrlV1 &&
          pathname !== "/__sillymaker/inspector"
        ) {
          next();
          return;
        }
        if (request.method !== "GET") {
          response.statusCode = 405;
          response.end("method not allowed");
          return;
        }
        void server
          .transformIndexHtml(inspectorPageUrlV1, createInspectorPageHtmlInternalV1())
          .then((html) => {
            response.statusCode = 200;
            response.setHeader("content-type", "text/html; charset=utf-8");
            response.end(html);
          })
          .catch((error: unknown) => {
            response.statusCode = 500;
            response.end(error instanceof Error ? error.message : "inspector html failed");
          });
      });
    },
  };
}
