// SPDX-License-Identifier: MIT
import type { Plugin, ViteDevServer } from "vite";

import type { ProjectModuleRefV1 } from "../project/config-types.ts";
import { accessibleApplicationBootShellHtmlV1 } from "../desktop/application-bootstrap-html.mts";

/**
 * The dev-only SillyMaker Studio page: `/__sillymaker/studio/` serves an
 * HTML shell (run through the dev server's HTML transforms so the Vite
 * client and the React preamble are injected) whose module entry mounts
 * `@sillymaker/studio` with the application's declared Studio binding.
 * `apply: "serve"` keeps every part of this out of builds, previews, and
 * the player bundle; the binding module is only ever imported here.
 */

export const studioPageUrlV1 = "/__sillymaker/studio/";

/** HTML contract with the game-page DevDock Studio shortcut. */
export const studioPageMetaNameV1 = "sillymaker-studio";

const studioEntryIdV1 = "/__sillymaker/studio-entry.tsx";

/** @internal Generated dev-only Author entry document. */
export function createStudioPageHtmlInternalV1(): string {
  return [
    "<!doctype html>",
    '<html lang="zh-CN">',
    "<head>",
    '<meta charset="utf-8" />',
    '<meta name="viewport" content="width=device-width, initial-scale=1" />',
    "<title>SillyMaker Studio</title>",
    "</head>",
    "<body>",
    accessibleApplicationBootShellHtmlV1({
      containerId: "sillymaker-studio-root",
      accessibleName: "SillyMaker Studio 启动状态",
      statusText: "SillyMaker Studio 正在启动…",
      bootstrap: Object.freeze({ revision: 1, entry: "author", target: "browser" }),
    }),
    `<script type="module" src="${studioEntryIdV1}"></script>`,
    "</body>",
    "</html>",
    "",
  ].join("\n");
}

function studioEntrySourceV1(studio: ProjectModuleRefV1): string {
  const bindingModuleId = `/${studio.module}`;
  return [
    "// Generated by sillymaker:studio (vite dev only).",
    'import { createDevServerRegionsIoV1, createDevServerSceneIoV1 } from "@sillymaker/studio";',
    'import { createStudioToolingHmrCoordinatorV1, createStudioToolingLiveCompositionV1, createStudioToolingReactPublicationV1 } from "@sillymaker/studio/composition";',
    'import { createDevServerMotionIoV1 } from "@sillymaker/ui/debug";',
    `import { ${studio.exportName} as bindingV1 } from ${JSON.stringify(bindingModuleId)};`,
    "",
    'const container = document.getElementById("sillymaker-studio-root");',
    'if (container === null) throw new Error("studio root element missing");',
    "const sceneIoV1 = createDevServerSceneIoV1();",
    "const motionIoV1 = createDevServerMotionIoV1();",
    "const regionsIoV1 = createDevServerRegionsIoV1();",
    "const reportStudioFailureV1 = (errorV1) => {",
    '  console.error("SillyMaker Studio live composition failed", errorV1);',
    "};",
    "const compositionV1 = createStudioToolingLiveCompositionV1({",
    '  profileId: "sillymaker.studio.live",',
    "  onDiagnostic: reportStudioFailureV1,",
    "});",
    "const reactPublicationV1 = createStudioToolingReactPublicationV1({",
    "  container,",
    "  reportFailure: reportStudioFailureV1,",
    "});",
    "let revisionV1 = 1;",
    "const initialPlanV1 = await compositionV1.mount({",
    "  revision: revisionV1,",
    "  binding: bindingV1,",
    "  sceneIo: sceneIoV1,",
    "  motionIo: motionIoV1,",
    "  regionsIo: regionsIoV1,",
    "});",
    "try {",
    "  await reactPublicationV1.mount(initialPlanV1);",
    "} catch (errorV1) {",
    "  reactPublicationV1.dispose();",
    "  try {",
    "    await compositionV1.dispose();",
    "  } catch (disposeErrorV1) {",
    "    reportStudioFailureV1(disposeErrorV1);",
    "  }",
    "  throw errorV1;",
    "}",
    "",
    "if (import.meta.hot !== undefined) {",
    "  const hmrV1 = createStudioToolingHmrCoordinatorV1({",
    "    composition: compositionV1,",
    "    resolveRoot(moduleV1) {",
    '      if (moduleV1 === undefined) throw new TypeError("accepted Studio module missing");',
    `      const nextBindingV1 = moduleV1[${JSON.stringify(studio.exportName)}];`,
    '      if (nextBindingV1 === undefined) throw new TypeError("accepted Studio binding missing");',
    "      revisionV1 += 1;",
    "      return {",
    "        revision: revisionV1,",
    "        binding: nextBindingV1,",
    "        sceneIo: sceneIoV1,",
    "        motionIo: motionIoV1,",
    "        regionsIo: regionsIoV1,",
    "      };",
    "    },",
    "    publish: (planV1, signalV1) => reactPublicationV1.publish(planV1, signalV1),",
    "    disposeRoot: () => reactPublicationV1.dispose(),",
    "    reportFailure: reportStudioFailureV1,",
    "  });",
    `  import.meta.hot.accept(${JSON.stringify(bindingModuleId)}, (moduleV1) => {`,
    "    hmrV1.accept(moduleV1);",
    "  });",
    "  import.meta.hot.dispose(() => {",
    "    void hmrV1.dispose();",
    "  });",
    "}",
    "",
  ].join("\n");
}

/** The `vite dev`-only Studio page plugin; absent when no binding is declared. */
export function studioPluginV1(studio: ProjectModuleRefV1): Plugin {
  return {
    name: "sillymaker:studio",
    apply: "serve",
    resolveId(id) {
      return id === studioEntryIdV1 ? studioEntryIdV1 : null;
    },
    load(id) {
      return id === studioEntryIdV1 ? studioEntrySourceV1(studio) : null;
    },
    transformIndexHtml: {
      order: "pre",
      handler(html) {
        // The Studio page is the destination, not the advertisement.
        if (html.includes('id="sillymaker-studio-root"')) return html;
        return {
          html,
          tags: [
            {
              tag: "meta",
              attrs: {
                name: studioPageMetaNameV1,
                content: studioPageUrlV1,
              },
              injectTo: "head",
            },
          ],
        };
      },
    },
    configureServer(server: ViteDevServer) {
      server.middlewares.use((request, response, next) => {
        const [pathname = ""] = (request.url ?? "").split("?", 2);
        if (pathname !== studioPageUrlV1 && pathname !== "/__sillymaker/studio") {
          next();
          return;
        }
        if (request.method !== "GET") {
          response.statusCode = 405;
          response.end("method not allowed");
          return;
        }
        void server
          .transformIndexHtml(studioPageUrlV1, createStudioPageHtmlInternalV1())
          .then((html) => {
            response.statusCode = 200;
            response.setHeader("content-type", "text/html; charset=utf-8");
            response.end(html);
          })
          .catch((error: unknown) => {
            response.statusCode = 500;
            response.end(error instanceof Error ? error.message : "studio html failed");
          });
      });
    },
  };
}
