// SPDX-License-Identifier: MIT
import type { Plugin, ViteDevServer } from "vite";

import type { ProjectModuleRefV1 } from "../project/config-types.ts";

/**
 * The dev-only SillyMaker Studio page: `/__sillymaker/studio/` serves an
 * HTML shell (run through the dev server's HTML transforms so the Vite
 * client and the React preamble are injected) whose module entry mounts
 * `@sillymaker/studio` with the application's declared Studio binding.
 * `apply: "serve"` keeps every part of this out of builds, previews, and
 * the player bundle; the binding module is only ever imported here.
 */

export const studioPageUrlV1 = "/__sillymaker/studio/";

/** HTML contract with the game-page DevDock Studio shortcut. */
export const studioPageMetaNameV1 = "sillymaker-studio";

const studioEntryIdV1 = "/__sillymaker/studio-entry.tsx";

function studioHtmlV1(): string {
  return [
    "<!doctype html>",
    '<html lang="zh-CN">',
    "<head>",
    '<meta charset="utf-8" />',
    '<meta name="viewport" content="width=device-width, initial-scale=1" />',
    "<title>SillyMaker Studio</title>",
    "</head>",
    "<body>",
    '<div id="sillymaker-studio-root"></div>',
    `<script type="module" src="${studioEntryIdV1}"></script>`,
    "</body>",
    "</html>",
    "",
  ].join("\n");
}

function studioEntrySourceV1(studio: ProjectModuleRefV1): string {
  return [
    "// Generated by sillymaker:studio (vite dev only).",
    'import { createRoot } from "react-dom/client";',
    "import {",
    "  StudioAppV1,",
    "  createDevServerRegionsIoV1,",
    "  createDevServerSceneIoV1,",
    '} from "@sillymaker/studio";',
    'import { createDevServerMotionIoV1 } from "@sillymaker/ui/debug";',
    `import { ${studio.exportName} as bindingV1 } from ${JSON.stringify(`/${studio.module}`)};`,
    "",
    'const container = document.getElementById("sillymaker-studio-root");',
    'if (container === null) throw new Error("studio root element missing");',
    "createRoot(container).render(",
    "  <StudioAppV1",
    "    binding={bindingV1}",
    "    io={createDevServerSceneIoV1()}",
    "    motionIo={createDevServerMotionIoV1()}",
    "    regionsIo={createDevServerRegionsIoV1()}",
    "  />,",
    ");",
    "",
  ].join("\n");
}

/** The `vite dev`-only Studio page plugin; absent when no binding is declared. */
export function studioPluginV1(studio: ProjectModuleRefV1): Plugin {
  return {
    name: "sillymaker:studio",
    apply: "serve",
    resolveId(id) {
      return id === studioEntryIdV1 ? studioEntryIdV1 : null;
    },
    load(id) {
      return id === studioEntryIdV1 ? studioEntrySourceV1(studio) : null;
    },
    transformIndexHtml: {
      order: "pre",
      handler(html) {
        // The Studio page is the destination, not the advertisement.
        if (html.includes('id="sillymaker-studio-root"')) return html;
        return {
          html,
          tags: [
            {
              tag: "meta",
              attrs: {
                name: studioPageMetaNameV1,
                content: studioPageUrlV1,
              },
              injectTo: "head",
            },
          ],
        };
      },
    },
    configureServer(server: ViteDevServer) {
      server.middlewares.use((request, response, next) => {
        const [pathname = ""] = (request.url ?? "").split("?", 2);
        if (pathname !== studioPageUrlV1 && pathname !== "/__sillymaker/studio") {
          next();
          return;
        }
        if (request.method !== "GET") {
          response.statusCode = 405;
          response.end("method not allowed");
          return;
        }
        void server
          .transformIndexHtml(studioPageUrlV1, studioHtmlV1())
          .then((html) => {
            response.statusCode = 200;
            response.setHeader("content-type", "text/html; charset=utf-8");
            response.end(html);
          })
          .catch((error: unknown) => {
            response.statusCode = 500;
            response.end(error instanceof Error ? error.message : "studio html failed");
          });
      });
    },
  };
}
